<a href="https://colab.research.google.com/github/MJanbandhu/PortugeseBankMarketingProject/blob/main/PRCP_1000.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Protugese Bank Mar
#  PRCP-1000-ProtugeseBank Portugese Bank Marketing Project

  The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe to a term deposit (variable y).

 # Problem Statement

1:-Prepare a complete data analysis report on the given data.

2:-Create a predictive model which will help the bank marketing team to know which customer will buy the product.

3:-Suggestions to the Bank market team to make  customers  buy the product.

In [ ]:
from google.colab import drive
#drive.mount('/content/drive')
from google.colab import drive
#drive.flush_and_unmount()

In [ ]:
# try to write something here

In [ ]:
import pandas

### We have do: Data Cleaning - convert to comma-separated csv

In [ ]:
# import csv

# RUN THE FOLLOWING IN CODE MODE
with open(r"C:\Users\GAISAAKS\Documents\Datamites Course Content\Projects\Datasets\PRCP-1000-Portuges Bank\bank-full.csv") as in_file, open(r"C:\Users\GAISAAKS\Documents\Datamites Course Content\Projects\Datasets\PRCP-1000-Portuges Bank\bank-full1.csv", 'w') as out_file:
    semicolonin = csv.reader(in_file, delimiter=';')
    commaout = csv.writer(out_file, delimiter=',')
    for row in semicolonin:
        commaout.writerow(row)

Change dataset file path to the localocation on your system

In [5]:
# import library
import pandas as pd

In [6]:
# data=pd.read_csv('bank-full.csv')

In [ ]:
# I uploaded File Using This
from google.colab import files

# Upload the dataset file
#uploaded = files.upload()

In [13]:
# here I'm try to read bank-additional-full.csv file
# Because it is mentioned in the document file ====   Kindly use Data>bank-additional>bank-additional-full.csv  for this use case.
data=pd.read_csv('bank-additional-full.csv')

In [14]:
 data

      age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"
0      56;"housemaid";"married";"basic.4y";"no";"no";...
1      57;"services";"married";"high.school";"unknown...
2      37;"services";"married";"high.school";"no";"ye...
3      40;"admin.";"married";"basic.6y";"no";"no";"no...
4      56;"services";"married";"high.school";"no";"no...
...                                                  ...
41183  73;"retired";"married";"professional.course";"...
41184  46;"blue-collar";"married";"professional.cours...
41185  56;"retired";"married";"university.degree";"no...
41186  44;"technician";"married";"professional.course...
41187  74;"retired";"married";"professional.course";"...

[41188 rows x 1 columns]

Now we have to do: Data cleaning - clean data set by removing semi colons and arrang data in good manner

In [15]:
# we are using some basic check to fetch column and dataset info

In [16]:
data.info

<bound method DataFrame.info of       age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"
0      56;"housemaid";"married";"basic.4y";"no";"no";...
1      57;"services";"married";"high.school";"unknown...
2      37;"services";"married";"high.school";"no";"ye...
3      40;"admin.";"married";"basic.6y";"no";"no";"no...
4      56;"services";"married";"high.school";"no";"no...
...                                                  ...
41183  73;"retired";"married";"professional.course";"...
41184  46;"blue-collar";"married";"professional.cours...
41185  56;"retired";"married";"university.degree";"no...
41186  44;"technician";"married";"professional.course...
41187  74;"retired";"married";"professional.course";"...

[41188 rows x 1 columns]>

In [17]:
data.columns

Index(['age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"'], dtype='object')

In [18]:
# we have to arrange

In [19]:
data = data['age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"'].str.split(';', expand=True)

In [20]:
data

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,56,"""housemaid""","""married""","""basic.4y""","""no""","""no""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
1,57,"""services""","""married""","""high.school""","""unknown""","""no""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
2,37,"""services""","""married""","""high.school""","""no""","""yes""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
3,40,"""admin.""","""married""","""basic.6y""","""no""","""no""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
4,56,"""services""","""married""","""high.school""","""no""","""no""","""yes""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,"""retired""","""married""","""professional.course""","""no""","""yes""","""no""","""cellular""","""nov""","""fri""",...,1,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""yes"""
41184,46,"""blue-collar""","""married""","""professional.course""","""no""","""no""","""no""","""cellular""","""nov""","""fri""",...,1,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""no"""
41185,56,"""retired""","""married""","""university.degree""","""no""","""yes""","""no""","""cellular""","""nov""","""fri""",...,2,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""no"""
41186,44,"""technician""","""married""","""professional.course""","""no""","""no""","""no""","""cellular""","""nov""","""fri""",...,1,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""yes"""
41187,74,"""retired""","""married""","""professional.course""","""no""","""yes""","""no""","""cellular""","""nov""","""fri""",...,3,999,1,"""failure""",-1.1,94.767,-50.8,1.028,4963.6,"""no"""

In [ ]:
# Now data in rows and columns but we have to rename the columns therfore columns name in digit

In [21]:
data.columns = ["age", "job", "marital", "education", "default", "housing", "loan","contact", "month","day_of_week","duration","campaign","pdays","previous","poutcome","emp.var.rate","cons.price.idx","cons.conf.idx","euribor3m","nr.employed","y"]

In [22]:
data

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,"""housemaid""","""married""","""basic.4y""","""no""","""no""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
1,57,"""services""","""married""","""high.school""","""unknown""","""no""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
2,37,"""services""","""married""","""high.school""","""no""","""yes""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
3,40,"""admin.""","""married""","""basic.6y""","""no""","""no""","""no""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
4,56,"""services""","""married""","""high.school""","""no""","""no""","""yes""","""telephone""","""may""","""mon""",...,1,999,0,"""nonexistent""",1.1,93.994,-36.4,4.857,5191,"""no"""
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,"""retired""","""married""","""professional.course""","""no""","""yes""","""no""","""cellular""","""nov""","""fri""",...,1,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""yes"""
41184,46,"""blue-collar""","""married""","""professional.course""","""no""","""no""","""no""","""cellular""","""nov""","""fri""",...,1,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""no"""
41185,56,"""retired""","""married""","""university.degree""","""no""","""yes""","""no""","""cellular""","""nov""","""fri""",...,2,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""no"""
41186,44,"""technician""","""married""","""professional.course""","""no""","""no""","""no""","""cellular""","""nov""","""fri""",...,1,999,0,"""nonexistent""",-1.1,94.767,-50.8,1.028,4963.6,"""yes"""
41187,74,"""retired""","""married""","""professional.course""","""no""","""yes""","""no""","""cellular""","""nov""","""fri""",...,3,999,1,"""failure""",-1.1,94.767,-50.8,1.028,4963.6,"""no"""

# Now we are trying to remove double quotation mark from data

In [24]:
data= data.apply(lambda x: x.str.replace('"', ''))
# Why we use lambda
# I think we aware from lambda function
#lambda function is used with the apply method to remove double quotes (") from all elements in a dataframe or a series.
# or series object

In [25]:
data

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no